name: carbon_app
description: >
  A Flutter application to visualize carbon emissions data.
  This app demonstrates data visualization with charts and manages state using Provider.

# 禁止將此包意外發布到 pub.dev
publish_to: "none"

# 應用程序版本和構建號
# `version` 格式為主版本號.次版本號.修訂號+構建號
version: 1.0.0+1

# Dart SDK 的最低和最高版本要求
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter # Flutter 的核心 SDK

  # iOS 風格的圖標支持
  cupertino_icons: ^1.0.8

  # 用於狀態管理
  provider: ^6.1.2

  # 用於圖表繪製的庫，代替已棄用的 charts_flutter
  fl_chart: ^0.69.0

  # 用於與 API 通信（如數據加載）
  http: ^1.2.2

  # 本地存儲，用於儲存用戶設置或偏好
  shared_preferences: ^2.0.13

  # 本地文件存取（如讀寫 JSON 文件）
  path_provider: ^2.0.15
  csv: ^6.0.0

  # 本地化支持，用於多語言環境
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  # 測試工具
  flutter_test:
    sdk: flutter

  # 用於代碼風格檢查的 lint 規則
  flutter_lints: ^5.0.0

  # 如果需要生成代碼（例如 JSON 序列化）
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# Flutter 配置部分
flutter:
  # 啟用 Material Icons 字體
  uses-material-design: true

  # 靜態資產，如圖片或 csv 數據
  assets:
    - assets/images/Pigeon.jpeg                        # Image asset
    - assets/data/ResidentialSector_CarbonEmissions_10ktonCO2e.csv
    - assets/data/ServiceIndustry_CarbonEmissions_10ktonCO2e.csv
    - assets/data/EnergySector_CarbonEmissions_10ktonCO2e.csv
    - assets/data/TransportationSector_CarbonEmissions_10ktonCO2e.csv
    - assets/data/Electricity_CarbonEmissions_10ktonCO2e.csv
    - assets/data/ManufacturingAndConstruction_CarbonEmissions_10ktonCO2e.csv
    - assets/data/TotalCarbonEmissions_AllSectors_10ktonCO2e.csv


  # 自定義字體
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
